### ISSUE TITLE
How to use

### ISSUE THREAD

**Issue by cissecedric** [markleusink/DominoServletUpload#1]
Hi Mark, could you please telle me how to open it in domino designer?
I'm used to .nsf files, but I don't know how to use/open your project in domino designer.
Maybe you use another IDE ? In this case I have the same question.. wich IDE and how ..

Many thanks,
Cédric

**Comment by markleusink** [comment]
The files in the 'nsf' folder of this repo are a so-called 'on-disk project' for an NSF file. Using Domino Designer, you can import them into an new (blank) database. See https://www.ibm.com/support/knowledgecenter/en/SSVRGU_9.0.1/user/wpd_srcecontrol_feature_setup.html and https://www.youtube.com/watch?v=wl_6LCkopMI for more information.

In short, the steps are:
* clone this project and import it into Designer (from package explorer > right-click > import > existing project)
* create a new NSF
* right-click on the NSF and choose Team Development > associate with existing on-disk project
* pick the project you just imported and let it import all design elements.

Good luck!
